### ISSUE TITLE
Discover and Implement Chat Functionality

### ISSUE THREAD

**Issue by wollmancsp** [wollmancsp/babysitter-front-end#10]
Per our requirements we need a chat feature, this ticket represents the work it takes to discover how we'll do it, and then implement it.

**Comment by PhillipBen** [comment]
Currently partially implemented. In progress.

**Comment by PhillipBen** [comment]
Chat has been improved, but is not yet considered complete yet by me.

**Comment by PhillipBen** [comment]
Completed as of 0.9.5
