### ISSUE TITLE
Load db with mock profiles

### ISSUE THREAD

**Issue by wollmancsp** [wollmancsp/babysitter-front-end#5]
Decide on how many mock profiles we would like to populate our app with and load them into a db (or databases)

**Comment by PhillipBen** [comment]
Profiles have been created. Password encryption has been added so we can login. We just need to finalize transactions so we can complete a user profile with all data needed to display on all pages

**Comment by PhillipBen** [comment]
Profiles are up and running. Just need to implement profile updates in front end.
